stages:
    - build
    
docker_cc:
    stage: build
    tags:
        - docker_cc
    before_script:
        - git branch -vva
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name

build_sing:
    stage: build
    tags:
        - atsccs68-shell
    before_script:
        - git branch -vva
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
    script:
        - whoami
        - pwd
        - git clone --recurse-submodules https://github.com/SeisSol/SeisSol
        - git clone https://github.com/7bits-register/convergence-tests.git tests
        - ls
        - cat /etc/os-release
        - cat test_singularity.sh
        - chmod +x test_singularity.sh
        - which singularity 
        - singularity --version
        - singularity pull library://7bits-register/collection/seissol-base.sif:sha256.99a798009fb5845985cc898de558d384bfc8b5354e955037c14896518d2f1820
        - ls
        - singularity run --nv -B $PWD:/home/$(whoami) --env GPU_VENDOR=nvidia --env GPU_MODEL=sm_61 --env HOST=snb ./seissol-base.sif_sha256.99a798009fb5845985cc898de558d384bfc8b5354e955037c14896518d2f1820.sif ./test_singularity.sh
