stages:
    - build 
ci_builder:
    stage: build
    tags:
        - ci_testing_cc
    before_script:
        - git branch -vva
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
    script:
        - whoami
        - pwd
        - echo $PATH
        - echo $NAME_TEST
