sudo: required

language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/old/netcdf-4.3.1.1.tar.gz

install:
 - sudo apt-get install -qq g++-4.7 gfortran openmpi-bin openmpi-common openmpi-dev libhdf5-openmpi-1.8.4 libhdf5-openmpi-dev
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
 - sudo update-alternatives --set gcc /usr/bin/gcc-4.7
 - tar -xaf netcdf-4.3.1.1.tar.gz
 - cd netcdf-4.3.1.1 && CC=mpicc ./configure --prefix=/usr && make && sudo make install && cd ..

script:
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=yes parallelization=hybrid arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=yes parallelization=hybrid commThread=yes arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=yes parallelization=hybrid netcdf=yes arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=yes parallelization=hybrid hdf5=yes arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=yes parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=yes parallelization=none arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=debug order=6 generatedKernels=yes parallelization=hybrid arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=no parallelization=mpi arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=no parallelization=mpi netcdf=yes arch=dsnb compiler=gcc -j2
 - scons -f SConstruct_generatedKernels compileMode=release order=6 generatedKernels=no parallelization=none arch=dsnb compiler=gcc -j2
